### PR TITLE
Compatibility with multilanguage sites

### PR DESCRIPTION
**Pull request by mariavilaro**
I moved this commit to its own branch, please close #43 

This changes allows the generation of a sitemap.xml with all the pages in all the locales. It needs my other 
pull request in Translate Plugin https://github.com/rainlab/translate-plugin/pull/300 to work.

### CODE REVIEW

**Comment by LukeTowers** [comment]
I don't understand why this custom handling for the Translation plugin cannot be handled from within the translation plugin itself. Why do we need to check for the Translation plugin from within the RainLab.Pages plugin?

**Comment by mariavilaro** [comment]
I don't understand your question. We don't check the Translaton plugin from within the RainLab.Pages plugin. This is the sitemap plugin, I'm just adding compatibility with multilanguage to it. It needs to be aware of the enabled languages and be able to ask to Translatoin plugin for the correct slugs for each multilanguage page.

**Comment by mariavilaro** [comment]
You can see an example of the result sitemap.xml here for example http://www.kendu.com/sitemap.xml

**Comment by LukeTowers** [comment]
I misstyped, I meant the RainLab.Sitemap plugin. My question is moreso why can't this be handled from within the event handling done inside the RainLab.Translate plugin?

**Comment by mariavilaro** [comment]
If it's possible, I don't know how. How can the Translate plugin know that we are asking for a sitemap and that it should give all the urls available for a page in all languages?

Another solution would be to have different sitemaps for each language, passing the locale as part of the url, like site.com/sitemap.en.xml site.com/sitemap.es.xml, but the majority of places I work use only one sitemap like this.

**Comment by LukeTowers** [comment]
You could potentially do it by creating a new event listener for each locale from the Translation plugin as such:

in the Translate Plugin.php
```php
if (!Classes\Translator::instance()->loadLocaleFromRequest()) {
    $translator = Classes\Translator::instance();
    $enabledLocales = Models\Locale::listEnabled();

    foreach ($enabledLocales as $locale => $nothing) {
        Event::listen('pages.menuitem.resolveItem', function ($type, $item, $url, $theme) use ($locale, $translator) {
            if ($type == 'cms-page') {
                if (!empty($locale)) $translator->setlocale($locale, false);
                return Behaviors\TranslatablePageUrl::resolveMenuItem($item, $url, $theme);
            }
        });
    }
}

**Comment by LukeTowers** [comment]
@mariavilaro does my example work to accomplish what you're looking for?

**Comment by mariavilaro** [comment]
mmmmm I'm not sure. The idea is good, but then the sitemap plugin receives one url without locale (with the slug in the default language or the language from session if it exists) and after that the list of urls with locale. For example this was my result checking sitemap.xml after browsing the site in spanish:

<url>
<loc>http://localhost/testsite/slug-en-espanol</loc>
...
</url>
<url>
<loc>http://localhost/testsite/en/slug-in-english</loc>
...
</url>
<url>
<loc>http://localhost/testsite/es/slug-en-espanol</loc>
...
</url>

http://localhost/testsite/slug-en-espanol doesn't exist and returns 404.

I really think the sitemap plugin should be aware that a site is multilanguage checking for the Translate plugin. And maybe it should even be able to generate different sitemaps for each language (as google recommends if I'm not mistaken... I'm not an expert at all).

If you really think this plugin should not be more complex than it is, maybe we should make a different sitemap-multilanguage plugin specifically for multilanguage sites?

**Comment by mariavilaro** [comment]
Hi any news about this? I'm using my modifications in Sitemap and Translate plugins in 5 different sites now, and not being able to update is a PITA. My first pull request about this was december last year (https://github.com/rainlab/translate-plugin/pull/199#issuecomment-269056569)... pretty please do something about it.

**Comment by mariavilaro** [comment]
I even submitted a bounty, had completely forgotten it. FFS close the issue https://github.com/rainlab/sitemap-plugin/issues/37 and claim the bounty https://www.bountysource.com/issues/37451356-does-not-work-with-properly-with-translated-urls

**Comment by LukeTowers** [comment]
@mariavilaro I would love to resolve this I just don't have time to review it! The only problem I have with merging this is separation of concerns. The Sitemap plugin should not know or care about the existence of the Translate plugin, any changes should be handled from the Translate plugin itself only because the requested behaviour is to extend the Sitemap plugin to work better with the Translate plugin.

Is the only issue with my proposed solution above that it generates one URL for each page without a locale in the URL that causes it to not work for that one URL, while the rest of the URLs generated are valid and work correctly?

**Comment by mariavilaro** [comment]
I don't agree with you. I think a sitemap plugin SHOULD be aware that it's being used in a multilanguage site.

Yes, the only issue about your solution is exactly what you say.

**Comment by mariavilaro** [comment]
In fact, this is what google recommends: using rel="alternate" to indicate the presence of translations for a page.

https://support.google.com/webmasters/answer/2620865?hl=en

<url>
    <loc>http://www.example.com/english/</loc>
    <xhtml:link 
                 rel="alternate"
                 hreflang="de"
                 href="http://www.example.com/deutsch/"
                 />
    <xhtml:link 
                 rel="alternate"
                 hreflang="de-ch"
                 href="http://www.example.com/schweiz-deutsch/"
                 />
    <xhtml:link 
                 rel="alternate"
                 hreflang="en"
                 href="http://www.example.com/english/"
                 />
  </url>

**Comment by LukeTowers** [comment]
Okay, I see two solutions here.

1. We keep the Sitemap plugin unaware about the presence of the Translate plugin and fix the bug causing the first URL to be incorrect
2. We add full support for the Translate plugin in the generation of sitemaps according to Google's specifications. 

I like your suggestion and think 2 would be a better overall resolution. However, we'll need to figure out the best way to accomplish that. If you'd like to make a new Pull Request that would generate the sitemap for multilanguage sites as you suggested, that would be fantastic!

Thanks for all your work on this, it's much appreciated!

**Comment by LukeTowers** [comment]
Closing in favour of #55

**Pull request closed without merging**
