### PR TITLE
Update the version

### PR DESCRIPTION
**Pull request by gergo85**
There is a very old version (Nov 22, 2016) on the Market.

### CODE REVIEW

**Comment by LukeTowers** [comment]
This is waiting on the multiline update message changes to be approved.

**Comment by gergo85** [comment]
Alright.

**Comment by bennothommo** [comment]
@gergo85 If you would like to get the version release happening, please feel free to change the version description to a one-liner like before. If possible, would you also be able to change the translation codes to their country names in the description?

**Comment by gergo85** [comment]
@bennothommo I made it.

**Comment by LukeTowers** [comment]
@bennothommo I believe the multiline updates are already in core?

**Comment by bennothommo** [comment]
@LukeTowers the functionality exists, but I was under the impression the marketplace still only shows the one line. Is that no longer the case?

**Comment by w20k** [comment]
@bennothommo it should be working, that's for sure. I've checked it after we made it stable few months ago, or so.

**Pull request merged**
