### PR TITLE
Added Turkish Language Translations and Permissions for Definitions

### PR DESCRIPTION
**Pull request by drtzack**

### CODE REVIEW

**Comment by SaifurRahmanMohsin** [comment]
+1. Hope this is pulled soon as it adds permissions.

**Comment by daftspunk** [comment]
Thanks

**Comment by drtzack** [comment]
It took almost 6 months. Wow.

**Comment by daftspunk** [comment]
@drtzack Ping me in IRC for escalations (username daftspunk or spunky)

**Pull request merged**
