### PR TITLE
Change the name of tab

### PR DESCRIPTION
**Pull request by gergo85**

### CODE REVIEW

**Comment by daftspunk** [comment]
*No reason provided.*

**Comment by daftspunk** [comment]
Just kidding, @gergo85 can you tell us more about what is going on here? Why are we changing this? Please, I beg you, make this the last time I have to ask this from you.

**Comment by gergo85** [comment]
Sorry. The tab contains the definition of the sitemap. So I thought the name of tab should be Definition instead of the plugin name.

**Comment by daftspunk** [comment]
> **This renames the tab from 'Sitemap' to 'Definition'.** The tab contains the definition of the sitemap. So I thought the name of tab should be Definition instead of the plugin name.

The part in bold is the part we need the most. Looking at "Files changed" tab in GitHub isn't always self explanatory like this. Thanks heaps.

**Pull request merged**
